<div class="navbar-wrapper">
    <div class="container-top">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Sitio</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <?php foreach ($this->container as $page) { ?>
                            <?php // @var $page Zend\Navigation\Page\Mvc ?>
                            <?php // when using partials we need to manually check for ACL conditions ?>
                            <?php
                            if (!$page->isVisible() || !$this->navigation()->accept($page)) {
                                continue;
                            }
                            ?>
                            <?php $hasChildren = $page->hasPages(); ?>
                            <?php if (!$hasChildren) { ?>
                                <li>
                                    <a href="<?php echo $page->getHref() ?>">
                                        <?php
                                        if ($page->get("icon")) {
                                            echo '<i class="' . $page->get("icon") . '"></i> ';
                                        }
                                        ?>
                                        <?php echo $page->getLabel() ?>
                                    </a>
                                </li>
                            <?php } else { ?>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        <?php
                                        if ($page->get("icon")) {
                                            echo '<i class="' . $page->get("icon") . '"></i>  ';
                                        }
                                        ?>
                                        <?php echo $page->getLabel() ?> <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <?php foreach ($page->getPages() as $child) { ?>
                                            <?php // when using partials we need to manually check for ACL conditions  ?>
                                            <?php
                                            if (!$child->isVisible() || !$this->navigation()->accept($child)) {
                                                continue;
                                            }
                                            ?>
                                            <li>
                                                <a href="<?php echo $child->getHref() ?>">
                                                    <?php echo $child->getLabel() ?>
                                                </a>
                                            </li>
                                        <?php } ?>
                                    </ul>
                                </li>
                            <?php } ?>
                        <?php } ?>
                    </ul>
                    <form class="navbar-form navbar-right" role="search">
                        <a href="/login/" class="btn btn-success" role="button"><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span></a>
                    </form>
                </div>
            </div>
        </nav>
    </div>
</div>