<hgroup id="login-title" class="large-margin-bottom">
    <h1 class="thin">Identifíquese</h1>
    <h5>Panel de administración</h5>
</hgroup>

<div id="form-wrapper">

    <div id="form-block" class="scratch-metal">
        <div id="form-viewport">

            <form method="post" action="" id="form-login" class="input-wrapper blue-gradient glossy" title="Entrar">
                <ul class="inputs black-input large">
                    <!-- The autocomplete="off" attributes is the only way to prevent webkit browsers from filling the inputs with yellow -->
                    <li><span class="icon-user mid-margin-right"></span><input type="text" name="login" id="login" value="" class="input-unstyled" placeholder="Usuario" autocomplete="off"></li>
                    <li><span class="icon-lock mid-margin-right"></span><input type="password" name="pass" id="pass" value="" class="input-unstyled" placeholder="Contraseña" autocomplete="off"></li>
                </ul>

                <p class="button-height">
                    <button type="submit" class="button glossy float-right" id="login">Entrar</button>
                    <input type="checkbox" name="remind" id="remind" value="1" checked="checked" class="switch tiny mid-margin-right with-tooltip" title="Enable auto-login">
                    <label for="remind">Recordarme</label>
                </p>
            </form>

            <form method="post" action="" id="form-password" class="input-wrapper orange-gradient glossy" title="Contraseña">

                <p class="message">
                    Si no recuerda su contraseña, solicite una nueva a su dirección de correo electrónico:
                    <span class="block-arrow"><span></span></span>
                </p>

                <ul class="inputs black-input large">
                    <li><span class="icon-mail mid-margin-right"></span><input type="email" name="mail" id="mail" value="" class="input-unstyled" placeholder="Su correo electrónico" autocomplete="off"></li>
                </ul>

                <button type="submit" class="button glossy full-width" id="send-password">Enviar nueva contraseña</button>

            </form>

            <form method="post" action="" id="form-register" class="input-wrapper green-gradient glossy" title="Registrar">

                <p class="message">
                    ¿Nuevo usuario? Registrese para obtener acceso a nuestro sistema:
                    <span class="block-arrow"><span></span></span>
                </p>

                <ul class="inputs black-input large">
                    <li><span class="icon-card mid-margin-right"></span><input type="text" name="name" id="name-register" value="" class="input-unstyled" placeholder="Nombres y Apellidos" autocomplete="off"></li>
                    <li><span class="icon-mail mid-margin-right"></span><input type="email" name="mail" id="mail-register" value="" class="input-unstyled" placeholder="Correo electrónico" autocomplete="off"></li>
                </ul>
                <ul class="inputs black-input large">
                    <li><span class="icon-user mid-margin-right"></span><input type="text" name="login" id="login-register" value="" class="input-unstyled" placeholder="Usuario" autocomplete="off"></li>
                    <li><span class="icon-lock mid-margin-right"></span><input type="password" name="pass" id="pass-register" value="" class="input-unstyled" placeholder="Contraseña" autocomplete="off"></li>
                </ul>

                <button type="submit" class="button glossy full-width" id="send-register">Registrar</button>

            </form>

        </div>
    </div>

</div>