<?php $bg = ($this->app[strtolower(getenv('MODULO'))][2]) ? $this->app[strtolower(getenv('MODULO'))][2] : '#3c4044' ?>
<div class="row featurette">
    <div class="col-md-12">
        <div class="jumbotron" style="
             color: white;
             background: <?php echo $bg ?> url(../img/textures/grid.png);
             background: -webkit-gradient(linear, left top, left bottom, from(rgba(0, 0, 0, 0.4)), to(rgba(0, 0, 0, 0))), <?php echo $bg ?> url(../img/textures/grid.png);
             background: -webkit-linear-gradient( top, rgba(0,0,0,0.4), rgba(0,0,0,0)), <?php echo $bg ?> url(../img/textures/grid.png);
             background: -moz-linear-gradient( top, rgba(0,0,0,0.4), rgba(0,0,0,0)), <?php echo $bg ?> url(../img/textures/grid.png);
             background: -ms-linear-gradient( top, rgba(0,0,0,0.4), rgba(0,0,0,0)), <?php echo $bg ?> url(../img/textures/grid.png);
             background: -o-linear-gradient( top, rgba(0,0,0,0.4), rgba(0,0,0,0)), <?php echo $bg ?> url(../img/textures/grid.png);
             background: linear-gradient( top, rgba(0,0,0,0.4), rgba(0,0,0,0)), <?php echo $bg ?> url(../img/textures/grid.png);
             ">
                 <?php if (getenv('ORGANIZACION') == 'default'): ?>
                <h1><?php echo getenv('NETWORK') ?> <small><?php echo ucfirst(getenv('MODULO')) ?></small></h1>
                <h2>Portada de aplicación</h2>
            <?php else: ?>
                <h1><?php echo getenv('NETWORK') ?> <small><?php echo ucfirst(getenv('MODULO')) ?></small></h1>
                <h2><?php echo $this->org[getenv('ORGANIZACION')] ?></h2>
            <?php endif ?>
        </div>
        <h3 class="featurette-heading"><?php echo $this->app[strtolower(getenv('MODULO'))][0] ?></h3>
        <p class="lead"><?php echo $this->app[strtolower(getenv('MODULO'))][1] ?></p>
    </div>
</div>