
<noscript class="message black-gradient simpler">Your browser does not support JavaScript! Some features won't work as expected...</noscript>

<hgroup id="main-title" class="thin">
    <h1>Escritorio</h1>
    <h2><?php echo $this->dateFormat(new DateTime(), \IntlDateFormatter::GREGORIAN, IntlDateFormatter::NONE, "es_VE"); ?> <strong><?php echo $this->dateFormat(new DateTime(), \IntlDateFormatter::NONE, IntlDateFormatter::SHORT, "en_US"); ?></strong></h2>
</hgroup>

<div class="dashboard">

    <div class="columns">

        <div class="nine-columns twelve-columns-mobile" id="demo-chart">
            <!-- This div will hold the chart generated in the footer -->
        </div>

        <div class="three-columns twelve-columns-mobile new-row-mobile">
            <ul class="stats split-on-mobile">
                <li><a href="#">
                        <strong>21</strong> Nuevas <br>Interacciones
                    </a></li>
                <li><a href="#">
                        <strong>15</strong> Cuentas <br>conectadas
                    </a></li>
                <li>
                    <strong>5</strong> Nuevos <br>servicios
                </li>
                <li>
                    <strong>235</strong> Nuevas <br>notificaciones
                </li>
            </ul>
        </div>

    </div>

</div>



<div class="with-padding">

    <table class="table responsive-table responsive-table-on dataTable sorting-advanced">
        <thead>
            <tr>
                <th scope="col"><input type="checkbox" name="check-all" id="check-all" value="1"></th>
                <th scope="col">Nombres de dominio</th>
                <th scope="col" width="140" class="hide-on-mobile">Registro</th>
                <th scope="col" width="140" class="hide-on-mobile">Vencimiento</th>
                <th scope="col" width="120" class="align-center hide-on-mobile">Acciones</th>
            </tr>
        </thead>
        <tbody>
            <tr itemid="3">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-3" value="3"></th>
                <td><a href="#">administrador.com.ve</a></td><td>10/03/2016</td><td>10/03/2017</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="4">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-4" value="4"></th>
                <td><a href="#">alas.com.ve</a></td><td>11/03/2016</td><td>11/03/2017</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="5">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-5" value="5"></th>
                <td><a href="#">ccr.com.ve</a></td><td>06/03/2016</td><td>06/03/2017</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="6">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-6" value="6"></th>
                <td><a href="#">coderic.com.ve</a></td><td>26/10/2015</td><td>26/10/2016</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="7">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-7" value="7"></th>
                <td><a href="#">coderic.org.ve</a></td><td>26/10/2015</td><td>26/10/2016</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="9">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-9" value="9"></th>
                <td><a href="#">contaduria.com.ve</a></td><td>06/03/2016</td><td>06/03/2017</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="10">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-10" value="10"></th>
                <td><a href="#">drpc.com.ve</a></td><td>17/11/2015</td><td>17/11/2016</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="11">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-11" value="11"></th>
                <td><a href="#">educativo.com.ve</a></td><td>10/03/2016</td><td>10/03/2017</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="12">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-12" value="12"></th>
                <td><a href="#">elgranodemostaza.com.ve</a></td><td>12/02/2016</td><td>12/02/2017</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="13">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-13" value="13"></th>
                <td><a href="#">encomiendas.com.ve</a></td><td>10/03/2016</td><td>10/03/2017</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="14">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-14" value="14"></th>
                <td><a href="#">franciscosilva.com.ve</a></td><td>20/02/2015</td><td>20/02/2017</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="15">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-15" value="15"></th>
                <td><a href="#">grancaracas.com.ve</a></td><td>14/07/2016</td><td>14/07/2017</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="16">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-16" value="16"></th>
                <td><a href="#">iglesiacristiana.com.ve</a></td><td>26/10/2015</td><td>26/10/2016</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="17">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-17" value="17"></th>
                <td><a href="#">juridico.com.ve</a></td><td>10/03/2016</td><td>10/03/2017</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="18">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-18" value="18"></th>
                <td><a href="#">lalocuradeljardinero.com.ve</a></td><td>15/02/2016</td><td>15/02/2017</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="19">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-19" value="19"></th>
                <td><a href="#">magalyvasquez.com.ve</a></td><td>16/07/2016</td><td>16/07/2017</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="20">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-20" value="20"></th>
                <td><a href="#">mecamotores.com.ve</a></td><td>12/07/2016</td><td>12/07/2017</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="21">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-21" value="21"></th>
                <td><a href="#">mientrasespero.com.ve</a></td><td>13/02/2016</td><td>13/02/2017</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="22">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-22" value="22"></th>
                <td><a href="#">neftaliyagua.com.ve</a></td><td>02/02/2010</td><td>02/02/2017</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="23">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-23" value="23"></th>
                <td><a href="#">noticiasaldia.com.ve</a></td><td>19/11/2015</td><td>19/11/2016</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="24">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-24" value="24"></th>
                <td><a href="#">nuvipa.com.ve</a></td><td>19/11/2015</td><td>19/11/2016</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="25">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-25" value="25"></th>
                <td><a href="#">portero.com.ve</a></td><td>06/03/2016</td><td>06/03/2017</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="26">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-26" value="26"></th>
                <td><a href="#">protejo.com.ve</a></td><td>06/04/2016</td><td>06/04/2017</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="27">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-27" value="27"></th>
                <td><a href="#">sandrayonekura.com.ve</a></td><td>26/10/2015</td><td>26/10/2016</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="28">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-28" value="28"></th>
                <td><a href="#">sdv.com.ve</a></td><td>17/11/2015</td><td>17/11/2016</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="29">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-29" value="29"></th>
                <td><a href="#">tecnicservice.com.ve</a></td><td>01/02/2015</td><td>01/02/2017</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="30">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-30" value="30"></th>
                <td><a href="#">transportes.com.ve</a></td><td>10/03/2016</td><td>10/03/2017</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="31">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-31" value="31"></th>
                <td><a href="#">tribunapublica.com.ve</a></td><td>10/11/2015</td><td>10/11/2016</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="31">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-31" value="31"></th>
                <td><a href="#">unanimes.com.ve</a></td><td>03/11/2015</td><td>03/11/2016</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="31">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-31" value="31"></th>
                <td><a href="#">unanimes.org.ve</a></td><td>03/11/2015</td><td>03/11/2016</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="31">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-31" value="31"></th>
                <td><a href="#">unitaxi.com.ve</a></td><td>08/08/2014</td><td>08/08/2016</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="31">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-31" value="31"></th>
                <td><a href="#">vacante.com.ve</a></td><td>17/11/2015</td><td>17/11/2016</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>
            <tr itemid="31">
                <th scope="row" class="checkbox-cell"><input type="checkbox" name="checked[]" id="check-31" value="31"></th>
                <td><a href="#">vitae.com.ve</a></td><td>17/11/2015</td><td>17/11/2016</td>
                <td class="low-padding align-center">
                    <a href="#" class="button blue-gradient glossy icon-tick with-tooltip" title=""></a>
                    <a href="#" class="button green-gradient glossy icon-page-list with-tooltip" title=""></a>
                    <a href="#" class="button red-gradient glossy icon-drawer with-tooltip archivar navigable-ajax" title=""></a>
                </td>
            </tr>

        </tbody>
    </table>
</div>



</div>

<script type="text/javascript">
<?php $this->inlineScript()->captureStart(); ?>


    var table = $('.sorting-advanced');
    table.dataTable({
        'oLanguage': {
            "sUrl": "/js/es_VE.json"
        },
        'aoColumnDefs': [
            {'bSortable': false, 'aTargets': [0, $(this).next('th').length - 1]}
        ],
        'sPaginationType': 'full_numbers',
        'fnInitComplete': function (oSettings)
        {
// Style length select
            table.closest('.dataTables_wrapper').find('.dataTables_length select').addClass('select blue-gradient glossy').styleSelect();
            tableStyled = true;
        }
    });


    var chartInit = false,
            drawVisitorsChart = function ()
            {
                // Create our data table.
                var data = new google.visualization.DataTable();
                var raw_data = [['Intención', 50, 73, 104, 129, 146, 176, 139, 149, 218, 194, 96, 53],
                    ['Productividad', 82, 77, 98, 94, 105, 81, 104, 104, 92, 83, 107, 91],
                    ['Desempeño', 50, 39, 39, 41, 47, 49, 59, 59, 52, 64, 59, 51],
                    ['Portergado', 45, 35, 35, 39, 53, 76, 56, 59, 48, 40, 48, 21]];

                var months = ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'];

                data.addColumn('string', 'Month');
                for (var i = 0; i < raw_data.length; ++i)
                {
                    data.addColumn('number', raw_data[i][0]);
                }

                data.addRows(months.length);

                for (var j = 0; j < months.length; ++j)
                {
                    data.setValue(j, 0, months[j]);
                }
                for (var i = 0; i < raw_data.length; ++i)
                {
                    for (var j = 1; j < raw_data[i].length; ++j)
                    {
                        data.setValue(j - 1, i + 1, raw_data[i][j]);
                    }
                }

                // Create and draw the visualization.
                // Learn more on configuration for the LineChart: http://code.google.com/apis/chart/interactive/docs/gallery/linechart.html
                var div = $('#demo-chart'),
                        divWidth = div.width();
                new google.visualization.LineChart(div.get(0)).draw(data, {
                    title: 'Estadísticas mensual de desempeño',
                    width: divWidth,
                    height: $.template.mediaQuery.is('mobile') ? 180 : 265,
                    legend: 'right',
                    yAxis: {title: '(thousands)'},
                    backgroundColor: ($.template.ie7 || $.template.ie8) ? '#494C50' : 'transparent', // IE8 and lower do not support transparency
                    legendTextStyle: {color: 'white'},
                    titleTextStyle: {color: 'white'},
                    hAxis: {
                        textStyle: {color: 'white'}
                    },
                    vAxis: {
                        textStyle: {color: 'white'},
                        baselineColor: '#666666'
                    },
                    chartArea: {
                        top: 35,
                        left: 30,
                        width: divWidth - 40
                    },
                    legend: 'bottom'
                });


                // Ready
                chartInit = true;
            };

    // Load the Visualization API and the piechart package.
    google.load('visualization', '1', {
        'packages': ['corechart']
    });

    // Set a callback to run when the Google Visualization API is loaded.
    google.setOnLoadCallback(drawVisitorsChart);

    // Watch for block resizing
    $('#demo-chart').widthchange(drawVisitorsChart);

    // Respond.js hook (media query polyfill)
    $(document).on('respond-ready', drawVisitorsChart);

<?php $this->inlineScript()->captureEnd(); ?>
</script>